title: Regorus Playground
email: anakrish@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  Run Regorus in a browser via WASM
url: "https://anakrish.github.io"
baseurl: "/"
include: ["examples", "node_modules", "pkg"]
# Build settings
#theme: minimal

