[package]
name = "regorus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
semver = "1.0.20"
serde = {version = "1.0.150", features = ["derive", "rc"] }
serde_json = {version = "1.0.89", features = ["arbitrary_precision"] }
serde_yaml = "0.9.16"
log = "0.4.17"
env_logger="0.10.0"
lazy_static = "1.4.0"
rand = "0.8.5"
data-encoding = "2.4.0"
regex = "1.10.2"
num = "0.4.1"
rust_decimal = { version = "1.33.1", features = ["serde-with-arbitrary-precision", "serde_json", "maths"] }

[dev-dependencies]
clap = { version = "4.4.7", features = ["derive"] }
test-generator = "0.3.1"
walkdir = "2.3.2"

[build-dependencies]
anyhow = "1.0.66"

[profile.release]
debug = true

[[test]]
name="opa"
harness=false
test=false

[[test]]
name="aci"
harness=false
test=false
